<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Description" data-toc-modified-id="Description-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Description</a></span></li><li><span><a href="#Import" data-toc-modified-id="Import-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Import</a></span></li><li><span><a href="#Array-creation" data-toc-modified-id="Array-creation-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Array creation</a></span></li><li><span><a href="#Prime-Numbers" data-toc-modified-id="Prime-Numbers-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Prime Numbers</a></span></li><li><span><a href="#Element-wise-Multiplication" data-toc-modified-id="Element-wise-Multiplication-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Element-wise Multiplication</a></span></li><li><span><a href="#Replacement" data-toc-modified-id="Replacement-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Replacement</a></span></li><li><span><a href="#Axis-Swap" data-toc-modified-id="Axis-Swap-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Axis Swap</a></span></li><li><span><a href="#Transposing" data-toc-modified-id="Transposing-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Transposing</a></span></li><li><span><a href="#Matrix-Multiplication" data-toc-modified-id="Matrix-Multiplication-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Matrix Multiplication</a></span></li><li><span><a href="#Cartesian-Prodoct" data-toc-modified-id="Cartesian-Prodoct-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Cartesian Prodoct</a></span></li><li><span><a href="#Sum-along-Axis" data-toc-modified-id="Sum-along-Axis-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Sum along Axis</a></span></li><li><span><a href="#Determinant" data-toc-modified-id="Determinant-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Determinant</a></span></li></ul></div>

## Description
Numpy is one of the most important Python libraries in data science. In this problem, we are going to get familiar with this library. 

**Note**: In the following cells, the input of each cell is the output of its previous cell. So, order of execution of the cells is important.

## Import 
Put all of your imports for this file in the below cell.

In [58]:
import numpy as np

#### Array creation
Create the followings to numpy array:
* A: a 3\*3 array that filled with number 1 to 9 row wise. like this:
$$
A = \left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right)
$$ 
* B: a 3\*3\*5 that filled with the numbers start from 11 and have steps of 3 to the end. The array should be filled first along the first dimension then the second dimension and at last the third dimension. like this:
$$
B[:, :, 0] = \left(\begin{array}{cc} 
11 & 20 & 29\\
14 & 23 & 32\\
17 & 26 & 35
\end{array}\right)
$$ 

In [59]:
A = np.arange(9) + 1
A = A.reshape(3,3)
print(A)

B = np.arange(3*3*5) * 3 + 11
B = B.reshape(3,3,5,order='F')
print(B[:,:,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 20 29]
 [14 23 32]
 [17 26 35]]


## Prime Numbers 
Replace the elements with prime values in the array A with 10.

In [60]:
def is_prime(n):
    if n == 1:
        return False;
    for i in range(2,n):
        if(n % i == 0):
            return False
    return True

for i in range(A.shape[0]) :
    for j in range(A.shape[1]):
        if(is_prime(A[i][j])):
            A[i][j] = 10

print(A)

[[ 1 10 10]
 [ 4 10  6]
 [10  8  9]]


## Element-wise Multiplication
Calculate the element wise multiplication of arrays A and B and put the result in B. Then print the result.

In [61]:
for i in range(B.shape[2]):
    B[:,:,i] = np.multiply(A,B[:,:,i])
print(B)

[[[  11   38   65   92  119]
  [ 200  470  740 1010 1280]
  [ 290  560  830 1100 1370]]

 [[  56  164  272  380  488]
  [ 230  500  770 1040 1310]
  [ 192  354  516  678  840]]

 [[ 170  440  710  980 1250]
  [ 208  424  640  856 1072]
  [ 315  558  801 1044 1287]]]


## Replacement
Replace the last slice of array B (B[:, :, 4]) with values of A. Then print the result.

In [62]:
B[:, :, 4] = A

for i in range(B.shape[2]):
    print("B[:,:,", i, "] = ", sep = "")
    print(B[:,:,i])

B[:,:,0] = 
[[ 11 200 290]
 [ 56 230 192]
 [170 208 315]]
B[:,:,1] = 
[[ 38 470 560]
 [164 500 354]
 [440 424 558]]
B[:,:,2] = 
[[ 65 740 830]
 [272 770 516]
 [710 640 801]]
B[:,:,3] = 
[[  92 1010 1100]
 [ 380 1040  678]
 [ 980  856 1044]]
B[:,:,4] = 
[[ 1 10 10]
 [ 4 10  6]
 [10  8  9]]


## Axis Swap 
Swap the first(B[:, :, 0]) and last(B[:, :, 4]) slice of the array B **only with one line of code**. Then print the result.

In [63]:
B = np.concatenate((np.atleast_3d(B[:,:,4]), np.atleast_3d(B[:,:,1:4]), np.atleast_3d(B[:,:,0])), axis=2)

for i in range(B.shape[2]):
    print("B[:,:,", i, "] = ", sep = "")
    print(B[:,:,i])

B[:,:,0] = 
[[ 1 10 10]
 [ 4 10  6]
 [10  8  9]]
B[:,:,1] = 
[[ 38 470 560]
 [164 500 354]
 [440 424 558]]
B[:,:,2] = 
[[ 65 740 830]
 [272 770 516]
 [710 640 801]]
B[:,:,3] = 
[[  92 1010 1100]
 [ 380 1040  678]
 [ 980  856 1044]]
B[:,:,4] = 
[[ 11 200 290]
 [ 56 230 192]
 [170 208 315]]


## Transposing 
Transpose the array B elements in each slice. Then print the result.

In [66]:
for i in range(B.shape[2]):
    B[:,:,i] = np.transpose(B[:,:,i])
    print("B[:,:,", i, "] = ", sep = "")
    print(B[:,:,i])
print(B)

B[:,:,0] = 
[[ 1  4 10]
 [10 10  8]
 [10  6  9]]
B[:,:,1] = 
[[ 38 164 440]
 [470 500 424]
 [560 354 558]]
B[:,:,2] = 
[[ 65 272 710]
 [740 770 640]
 [830 516 801]]
B[:,:,3] = 
[[  92  380  980]
 [1010 1040  856]
 [1100  678 1044]]
B[:,:,4] = 
[[ 11  56 170]
 [200 230 208]
 [290 192 315]]
[[[   1   38   65   92   11]
  [   4  164  272  380   56]
  [  10  440  710  980  170]]

 [[  10  470  740 1010  200]
  [  10  500  770 1040  230]
  [   8  424  640  856  208]]

 [[  10  560  830 1100  290]
  [   6  354  516  678  192]
  [   9  558  801 1044  315]]]


## Matrix Multiplication
Calculate the matrix multiplication of all slices of the array B. 
(B[:, :, 0] \* B[:, :, 1] \* B[:, :, 2] \* B[:, :, 3] \* B[:, :, 4]). Then print the result.

**Note**: the result should be a 3\*3 array. 

In [68]:
R = np.eye(3)
for i in range(B.shape[2]):
    R = np.matmul(R ,B[:,:,i])
    
print(R)

[[1.57164947e+13 1.42538533e+13 2.12990938e+13]
 [2.49852948e+13 2.26168386e+13 3.37545632e+13]
 [2.18312802e+13 1.97540806e+13 2.94853764e+13]]


## Cartesian Prodoct
Calculate the cartesian product of all columns of the array and put them in one slice. Then print the result.

**Note**: the result should be a 3\*3\*3\*3 array. 

In [69]:
CP = np.empty([3, 3, 3, 3])

for i in range(3):
    for j in range(3):
        for k in range(3):
            CP[i][j][k][0] = R[i][0]
            CP[i][j][k][1] = R[j][1]
            CP[i][j][k][2] = R[k][2]
            
print(CP)

[[[[1.57164947e+13 1.42538533e+13 2.12990938e+13]
   [1.57164947e+13 1.42538533e+13 3.37545632e+13]
   [1.57164947e+13 1.42538533e+13 2.94853764e+13]]

  [[1.57164947e+13 2.26168386e+13 2.12990938e+13]
   [1.57164947e+13 2.26168386e+13 3.37545632e+13]
   [1.57164947e+13 2.26168386e+13 2.94853764e+13]]

  [[1.57164947e+13 1.97540806e+13 2.12990938e+13]
   [1.57164947e+13 1.97540806e+13 3.37545632e+13]
   [1.57164947e+13 1.97540806e+13 2.94853764e+13]]]


 [[[2.49852948e+13 1.42538533e+13 2.12990938e+13]
   [2.49852948e+13 1.42538533e+13 3.37545632e+13]
   [2.49852948e+13 1.42538533e+13 2.94853764e+13]]

  [[2.49852948e+13 2.26168386e+13 2.12990938e+13]
   [2.49852948e+13 2.26168386e+13 3.37545632e+13]
   [2.49852948e+13 2.26168386e+13 2.94853764e+13]]

  [[2.49852948e+13 1.97540806e+13 2.12990938e+13]
   [2.49852948e+13 1.97540806e+13 3.37545632e+13]
   [2.49852948e+13 1.97540806e+13 2.94853764e+13]]]


 [[[2.18312802e+13 1.42538533e+13 2.12990938e+13]
   [2.18312802e+13 1.42538533e+13 

## Sum along Axis
Calculate the sum of values of the array along its two last dimensions. Then print it. 

**Note**: the result is a 3\*3 array. 

In [70]:
SP = np.sum(CP, axis=3)
SP = np.sum(SP, axis=2)
SP

array([[1.74450077e+14, 1.99539033e+14, 1.90950759e+14],
       [2.02256478e+14, 2.27345434e+14, 2.18757160e+14],
       [1.92794434e+14, 2.17883390e+14, 2.09295116e+14]])

## Determinant
Calculate the determinant of the array and print it.

In [72]:
np.linalg.det(SP) 

8.005072516878247e+24